### ISSUE TITLE
Can't run the training code!

### ISSUE THREAD

**Issue by kalyo-zjl** [anilbas/3DMMasSTN#1]
hi @anilbas,

Thanks for sharing the code!

I followed your readme to run the code, but there seemed to be some problems. Could you please give me some advice on the questions below?
In dagnn_3dmmasstn.m line 39, load('model/model.mat'), what should the model.mat be?
Besides, what is the training set, and how to create the imdb.mat? 

Thanks in advance!

**Comment by anilbas** [comment]
Hi @kalyo-zjl, 
-In dagnn_3dmmasstn.m line 39, load('model/model.mat'), what should the model.mat be?

The model.mat is the resampled expression model. You should be able to generate the model by following the instructions on the Usage & Training section and provide the resampled model (save the newmodel -the output of the prepareExpressionBFM.m- as a .mat file and load in the dagnn_3dmmasstn.m). 

-What is the training set, and how to create the imdb.mat?

The current version of the code can be modified easily to be worked with any training set. If you would like to use pre-trained VGG as a localiser, you can train the network using 224x224x3 face images. We used cropped images from the AFLW dataset for the training and UMDFaces datasets for the evaluation.
