### ISSUE TITLE
About pretrained model

### ISSUE THREAD

**Issue by mychina75** [anilbas/3DMMasSTN#2]
hi @anilbas,
Thank you for your great work.
I'd like to try some images, but can not find your model.
Where can I get your model for test? 
Thank you!

**Comment by anilbas** [comment]
Hi @mychina75,
Thank you for your interest.
We have realised that our network could get much better results using the [autonn wrapper](https://github.com/vlfeat/autonn) under MatConvNet. We will update the repo with the new structure and hopefully with a pre-trained model in the coming months. 
Kind regards,
Anil

**Comment by mychina75** [comment]
Thank you, @anilbas, I am looking forward to your new release.

**Comment by suvojit-0x55aa** [comment]
@anilbas any update on this ?

**Comment by ReverseSystem001** [comment]
@anilbas any update on this?
