### ISSUE TITLE
can't find vl_nnbilinearsampler

### ISSUE THREAD

**Issue by WangYanru-NJU** [anilbas/3DMMasSTN#3]
hi @anilbas,

Thanks for sharing the code!

I followed your readme to run the demo.m, but i can't find vl_nnbilinearsampler function. Could you please release that part of code?

sampler = vl_nnbilinearsampler(Images,grid);
demo (line 131)

Thanks in advance!

**Comment by patrikhuber** [comment]
Hi @2013211543,
`vl_nnbilinearsampler` is part of MatConvNet: http://www.vlfeat.org/matconvnet/mfiles/vl_nnbilinearsampler/.
So I suspect that you didn't install MatConvNet correctly, maybe didn't run `vl_setupnn` or something like that.

**Comment by WangYanru-NJU** [comment]
Thank you, @patrikhuber, I have fixed my problem with your advice.
