### ISSUE TITLE
How to obtain BFM_UV.mat?

### ISSUE THREAD

**Issue by marvin521** [anilbas/3DMMasSTN#8]
I want know the detailed way to obtain the BFM_UV.mat. Could you tell me the method? thanks.

**Comment by patrikhuber** [comment]
The `BFM_UV.mat` is in the [utils folder](https://github.com/anilbas/3DMMasSTN/blob/master/util/BFM_UV.mat). But I suppose you mean how the uv coordinates were generated. You can find more information about that in our [paper](http://openaccess.thecvf.com/content_ICCV_2017_workshops/papers/w17/Bas_3D_Morphable_Models_ICCV_2017_paper.pdf), Section 2.3, in the paragraph "Output grid". Hope that helps!

**Comment by ReverseSystem001** [comment]
> the detailed way to obtain the BFM_UV.mat

hi, do you find the detailed way to obtain the BFM_UV.mat now?
